### ISSUE TITLE
remove exception

### ISSUE THREAD

**Issue by ycenta** [ESGI-69/challenge-stack#49]

**Comment by mrpinkcat** [comment]
c koi @ycenta ?

**Comment by ycenta** [comment]
Toutes les exeptions qu'on avait (mises par defaut par symfony, par exemple pour les methods not allowed ect)

**Comment by mrpinkcat** [comment]
Ha oui ! bien vue

**Comment by Timdev0** [comment]
les exception ne sont pas affiché en prod normalement, j'ai fait une 403 et 404 custom, à vérifier sur la prod

**Comment by mrpinkcat** [comment]
> les exceptions ne sont pas affiché en prod normalement, j'ai fait une 403 et 404 custom, à vérifier sur la prod
